# Generated by Django 5.1.7 on 2025-03-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_books', to='app.book'),
        ),
        migrations.AlterField(
            model_name='studentbook',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_books', to='app.student'),
        ),
    ]
